name: Publish resume in JSONResume format as Github Page

on:
  push:
    branches: [ main ]

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v4
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: macchiato
          resume_filepath: resume.json
          output_filepath: docs/index.html
      - name: Check for changes in docs/index.html
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain docs/index.html)" ]; then
            echo "Changes detected in docs/index.html"
            echo "exit_code=0" >> $GITHUB_ENV
          else
            echo "No changes in docs/index.html"
            echo "exit_code=1" >> $GITHUB_ENV
          fi
      - name: Debug exit_code
        run: echo "Exit Code is $exit_code"
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: env.exit_code == 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
